-- Editor Settings
vim.wo.wrap = false
vim.opt.smartindent = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.termguicolors = true
vim.opt.relativenumber = true
vim.opt.number = true
